# Prometheus configuration for SIM-ONE MCP Server monitoring
# Scrapes metrics from application instances and system components

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # SIM-ONE MCP Server instances
  - job_name: 'simone-mcp-server'
    static_configs:
      - targets: ['mcp-server-1:8000', 'mcp-server-2:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379', 'redis-replica:6379']
    scrape_interval: 30s
    
  # Nginx monitoring (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    
  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']