blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: mailto:security@gorombo.com
    about: Please report vulnerabilities privately per SECURITY.md
  - name: Commercial licensing
    url: mailto:licensing@gorombo.com
    about: Ask about commercial terms if AGPL is not suitable
